In [1]:
from sklearn.linear_model import LinearRegression
from sklearn.datasets import load_boston
import pandas as pd
import numpy as np

In [41]:
boston = load_boston()
X, y, columns = boston.data, boston.target, boston.feature_names

In [42]:
pd.DataFrame(X, columns=columns).head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3  0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4  0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   

   PTRATIO       B  LSTAT  
0     15.3  396.90   4.98  
1     17.8  396.90   9.14  
2     17.8  392.83   4.03  
3     18.7  394.63   2.94  
4     18.7  396.90   5.33

In [43]:
y[0:5]

array([24. , 21.6, 34.7, 33.4, 36.2])

# 最小二乗法  

## sklearn

In [44]:
clf1 = LinearRegression().fit(X, y)

coef_df = pd.DataFrame(clf1.coef_,
                       index=boston.feature_names,
                       columns=['clf1'])
coef_df

clf1
CRIM     -0.108011
ZN        0.046420
INDUS     0.020559
CHAS      2.686734
NOX     -17.766611
RM        3.809865
AGE       0.000692
DIS      -1.475567
RAD       0.306049
TAX      -0.012335
PTRATIO  -0.952747
B         0.009312
LSTAT    -0.524758

## 自作  
w = (X.T X)^(-1)X.Ty

In [45]:
# 切片の追加
X = np.insert(X, 0, 1, axis=1)
pd.DataFrame(X).head()

0        1     2     3    4      5      6     7       8    9     10  \
0  1.0  0.00632  18.0  2.31  0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1  1.0  0.02731   0.0  7.07  0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2  1.0  0.02729   0.0  7.07  0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3  1.0  0.03237   0.0  2.18  0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4  1.0  0.06905   0.0  2.18  0.0  0.458  7.147  54.2  6.0622  3.0  222.0   

     11      12    13  
0  15.3  396.90  4.98  
1  17.8  396.90  9.14  
2  17.8  392.83  4.03  
3  18.7  394.63  2.94  
4  18.7  396.90  5.33

In [46]:
# X.T X
np.dot(X.T,  X)[0:5]

array([[5.06000000e+02, 1.82844292e+03, 5.75000000e+03, 5.63521000e+03,
        3.50000000e+01, 2.80675700e+02, 3.18002500e+03, 3.46989000e+04,
        1.92029160e+03, 4.83200000e+03, 2.06568000e+05, 9.33850000e+03,
        1.80477060e+05, 6.40245000e+03],
       [1.82844292e+03, 4.39703436e+04, 4.68702660e+02, 3.24790952e+04,
        6.48084600e+01, 1.22612317e+03, 1.08219511e+04, 1.68514980e+05,
        3.46627456e+03, 4.11186651e+04, 1.17307321e+06, 3.64715518e+04,
        4.99455291e+05, 3.72684187e+04],
       [5.75000000e+03, 4.68702660e+02, 3.40029000e+05, 2.09030900e+04,
        2.70000000e+02, 2.48444175e+03, 3.87184670e+04, 2.05485400e+05,
        3.82992940e+04, 2.29180000e+04, 1.72295450e+06, 9.61321500e+04,
        2.23960499e+06, 3.80196800e+04],
       [5.63521000e+03, 3.24790952e+04, 2.09030900e+04, 8.65256299e+04,
        4.45170000e+02, 3.43239536e+03, 3.44618165e+04, 4.49313490e+05,
        1.62206733e+04, 7.17656500e+04, 2.72134904e+06, 1.06875320e+05,
        1.897

In [51]:
#(X.T X)^(-1)X.Ty
w = np.dot(np.dot(np.linalg.inv(np.dot(X.T,  X)), X.T), y)
w

array([ 3.64594884e+01, -1.08011358e-01,  4.64204584e-02,  2.05586264e-02,
        2.68673382e+00, -1.77666112e+01,  3.80986521e+00,  6.92224640e-04,
       -1.47556685e+00,  3.06049479e-01, -1.23345939e-02, -9.52747232e-01,
        9.31168327e-03, -5.24758378e-01])

In [52]:
# 切片が入っているので1列以降を表示
w[1:]

array([-1.08011358e-01,  4.64204584e-02,  2.05586264e-02,  2.68673382e+00,
       -1.77666112e+01,  3.80986521e+00,  6.92224640e-04, -1.47556685e+00,
        3.06049479e-01, -1.23345939e-02, -9.52747232e-01,  9.31168327e-03,
       -5.24758378e-01])

In [50]:
coef_df["clf2"] = w[1:]
coef_df

clf1       clf2
CRIM     -0.108011  -0.108011
ZN        0.046420   0.046420
INDUS     0.020559   0.020559
CHAS      2.686734   2.686734
NOX     -17.766611 -17.766611
RM        3.809865   3.809865
AGE       0.000692   0.000692
DIS      -1.475567  -1.475567
RAD       0.306049   0.306049
TAX      -0.012335  -0.012335
PTRATIO  -0.952747  -0.952747
B         0.009312   0.009312
LSTAT    -0.524758  -0.524758